wilsvd/COMP4024_Coursework

CONTRIBUTING.md
GIT_GUIDE.md
README.md

Improved documentation regarding the git standards as well how to contribute to the repository
N/A

docs: add documentation for contributing and git standards

---

CONTRIBUTING.md
GIT_GUIDE.md
README.md

Add documentation for contributing and git conventions
N/A

Add documentation for contributing and git conventions

---

README.md

Adds Sam's name to .readme

---

README.md

Reverts wilsvd/COMP4024_Coursework#9

Revert "Adds Sam's name to .readme"

---

Assets/Animations.meta
Assets/Animations/Sword.controller
Assets/Animations/Sword.controller.meta
Assets/Animations/SwordAttack.anim
Assets/Animations/SwordAttack.anim.meta
Assets/Scenes/SampleScene.unity
Assets/Scripts/Pickup.cs
Assets/Scripts/SwordAttack.cs
Assets/Scripts/SwordAttack.cs.meta

feat: add sword animation on attack

---

Assets/Prefabs/Arrow.prefab
Assets/Prefabs/Arrow.prefab.meta
Assets/Prefabs/Sword.prefab
Assets/Scenes/SampleScene.unity
Assets/Scripts/Arrow.cs
Assets/Scripts/Arrow.cs.meta
Assets/Scripts/Bow.cs
Assets/Scripts/Bow.cs.meta
Assets/Scripts/PlayerAttack.cs
Assets/Scripts/PlayerPickup.cs
ProjectSettings/TagManager.asset

feat: add bow attack that uses an arrow

---

Assets/Animations/Boss.controller
Assets/Animations/Boss.controller.meta
Assets/Animations/BossAttack.anim
Assets/Animations/BossAttack.anim.meta
Assets/Animations/BossRun.anim
Assets/Animations/BossRun.anim.meta
Assets/Animations/Sword.controller
Assets/Scenes/SampleScene.unity
Assets/Scripts/Boss.cs
Assets/Scripts/BossRun.cs
Assets/Scripts/BossRun.cs.meta
Assets/Scripts/BossWeapon.cs
Assets/Scripts/BossWeapon.cs.meta
Assets/Scripts/PlayerMovement.cs
Assets/Scripts/healthPoints.cs
ProjectSettings/Physics2DSettings.asset
ProjectSettings/TagManager.asset

feat: add attack and run functionality for boss character

---

Assets/Prefabs/HealthCanvasboss.prefab
Assets/Prefabs/HealthCanvasboss.prefab.meta
Assets/Scenes/SampleScene.unity
Assets/Scripts/Arrow.cs
Assets/Scripts/Boss_Healthbar.cs
Assets/Scripts/Boss_Healthbar.cs.meta
Assets/Scripts/Slider_bossHP.cs
Assets/Scripts/Slider_bossHP.cs.meta
Assets/Scripts/Sword.cs
Assets/Scripts/healthPoints.cs

add healthbar to boss

---

Assets/Scenes/SampleScene.unity

fix: remove unused scripts

---

Assets/Scenes/LEVEL ONE.unity
Assets/Scenes/LEVEL THREE.unity
Assets/Scenes/LEVEL TWO.unity
Assets/Scripts/GameManager.cs
Assets/Scripts/NavTeleporter.cs
Assets/Scripts/Player/PlayerController.cs

Game timer resets on every level and decides whether the level is finished enabling user to go through the door.
N/A

feat: add game timer

---

Assets/Scenes/SampleScene.unity
Assets/Scripts/Boss/BossWeapon.cs
Assets/Scripts/Player/Arrow.cs
Assets/Scripts/Player/Bow.cs
Assets/Scripts/Player/Inventory.cs
Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/Sword.cs
Assets/Scripts/Player/healthPoints.cs
Assets/Tests/PlayTests/PickupTests.cs

feat: increase weapon damage when picking up weapon of same type

---

Assets/Prefabs/Boss.prefab
Assets/Prefabs/Player.prefab
Assets/Scenes/BOSS LEVEL.unity
Assets/Scenes/SampleScene.unity
Assets/Scripts/GameManager.cs
Assets/Scripts/Player/PlayerController.cs
Assets/Scripts/Player/healthPoints.cs

feat: add level reset when player death by boss and by falling

---

Assets/Prefabs/Player.prefab
Assets/Scenes/BOSS LEVEL.unity
Assets/Scenes/LEVEL ONE.unity
Assets/Scenes/LEVEL THREE.unity
Assets/Scenes/LEVEL TWO.unity
Assets/Scenes/NAV LEVEL.unity
Assets/Scripts/GameManager.cs
Assets/Scripts/Player/Inventory.cs
Assets/Scripts/Player/Player.cs
Assets/Scripts/Player/Player.cs.meta
Assets/Scripts/Player/PlayerController.cs
Assets/Scripts/Player/healthPoints.cs
ProjectSettings/TagManager.asset

feat: track player state across game scenes

---

Assets/Scenes/SampleScene.unity
Assets/Scripts/Boss/Boss_Healthbar.cs
Assets/Tests/PlayTests/HPbossTesting.cs
Assets/Tests/PlayTests/HPbossTesting.cs.meta

Test: boss HP

---

Assets/Scenes/LEVEL ONE.unity
Assets/Scenes/LEVEL THREE.unity
Assets/Scenes/LEVEL TWO.unity
Assets/Scripts/GameManager.cs
Assets/Scripts/Player/Player.cs
Assets/Scripts/Player/PlayerController.cs

fix: player inventory state is kept on boss level

---

Assets/Scenes/VICTORY_SCENE.unity
Assets/Scripts/GameManager.cs
ProjectSettings/EditorBuildSettings.asset

feat: add victory scene navigation

---

Assets/Tests/PlayTests/Boss/HPbossTesting.cs

Add boss die test

---

Assets/Scripts/Game/QuestionManager.cs
Assets/Scripts/Player/PlayerMovement.cs

fix: fix bug where you can keep selecting a new question by jumping

---

Assets/Scenes/VICTORY_SCENE.unity
Assets/Scripts/Game/GameManager.cs
Assets/Scripts/Game/QuestionManager.cs
ProjectSettings/TagManager.asset

feat: display final game score at victory scene

---

Assets/Scripts/Boss/Boss.cs
Assets/Scripts/Boss/BossHealth.cs
Assets/Scripts/Boss/BossHealthbar.cs
Assets/Scripts/Boss/BossRun.cs
Assets/Scripts/Boss/BossWeapon.cs
Assets/Scripts/Game/GameManager.cs
Assets/Scripts/Game/NavTeleporter.cs
Assets/Scripts/Game/QuestionManager.cs
Assets/Scripts/Game/TagAssigner.cs
Assets/Scripts/Player/Arrow.cs
Assets/Scripts/Player/Bow.cs
Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/PlayerHealth.cs
Assets/Scripts/Player/PlayerHealthbar.cs
Assets/Scripts/Player/PlayerInventory.cs
Assets/Scripts/Player/PlayerManager.cs
Assets/Scripts/Player/PlayerMovement.cs
Assets/Scripts/Player/PlayerPickup.cs
Assets/Scripts/Player/Sword.cs

docs: add documentation to the scripts

---

Assets/Scripts/Game/GameManager.cs

fix: reset game count on nav scene

---

README.md

docs: add wil name to contributors

---

README.md

docs: add links to design docs and inspirations
